### ISSUE TITLE
Haxe 4.2 features

### ISSUE THREAD

**Issue by markknol** [fdorg/flashdevelop#3232]
It would be nice if we could have support for the new Haxe 4.2 features in HaxeDevelop

* [ ] Module-level fields https://github.com/HaxeFoundation/haxe/issues/8460
* [ ] Abstract classes and functions https://github.com/HaxeFoundation/haxe-evolution/pull/69 / https://github.com/HaxeFoundation/haxe/issues/9716
* [ ] Rest arguments using `...` syntax https://github.com/HaxeFoundation/haxe/issues/9961
